### ISSUE TITLE
Add test with few example GEDCOM files

### ISSUE THREAD

**Issue by andy-z** [andy-z/ged4py#13]
Current bunch of unit tests is limited to data that is encode as strings in the Python code. It would be useful to add a bunch of sample GEDCOM files and a bunch of tests that read and parse those files.

**Comment by andy-z** [comment]
https://www.gedcom.org/samples.html has few samples but they are marked as GEDCOM 5.5.5 and they are relatively small.

**Comment by andy-z** [comment]
One thing that I realized is that I do not want trees of real people to appear in a public git repo, need to think of a way to structure things so that I could have non-published collection (or private collection) of files that could be tested separately.

**Comment by Tuisto59** [comment]
Hi Andy !
Using the demo files of the genealogy software to test gedcompy is a good idea.

A list of the most used familly tree software can be make - lot of them can be obselete and impossible to recover (here a list from the french page wikipedia https://fr.wikipedia.org/wiki/Logiciel_de_g%C3%A9n%C3%A9alogie).

This allows in particular to be able to test the parser with the different file encodings available to the software when it exports data to GEDCOM, too, if you wish to carry out tests, if you do not wish to have that gedcom in your repo, several solutions :

- convert the real data to fake data like transform every individual into fake data. But you can loss data for example if they have encoded character, also it's long because it's manually from the file.
- Use real people, but deceased from a long time, in Europe or in France the RGPD and CNIL allow that, because people are deceased from a long time (for example European noble lineage) it's part of common history.
- Also the language that you will use (for my part is french) allow you to use accented characters (é, è, ç, ï, ...) it will be different if the user is from spain, russia, swedish, etc...
- Some french software (geneatique and Heredis (proprietary), Ancestris (opensource)) have good example file of french monarchy familly tree, you can use them as example in the other tested software.

**Comment by andy-z** [comment]
After some thinking I decided that I want a separate private repo for the data files and tests that run on those files, main reasons are:
- I do not want to fill `ged4py` repo with large data files that are not critical for its function
- some of the GEDCOM files that I people send me have some personal info and I do not have time to anonymize that data.

The new repo is called `ged4py_testdata` but it is my private repo and I don't plan to give anyone access to it but I will use it as a development tool for testing `ged4py`. I'll collect some reasonable set of files there and add tests for basic functionality and maybe some specific features as I go along.

**Comment by andy-z** [comment]
Closing this issue, I will continue adding stuff to my private `ged4py_testdata` repo as I go, that will probably trigger more tickets here.
