### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by VK6TGQ** [andy-z/ged4py#18]
* GEDCOM parser for Python version: 0.2.0
* Python version: 3.7
* Operating System: Linux (Ubuntu)

### Description
Hi andy-z, are you able to provide any sample code for using ged4py?  

### What I Did
By looking through the test code, I have been able open and parse a gedcom file to Level 1 Tags, but I can't work out how to access Level 2 Tags.  For example DATE and PLACE of a MARRIAGE under a FAM tag.  Any guidance you could provide would be greatly appreciated.

Kind Regards, Brian

**Comment by andy-z** [comment]
Hi Brian,

just checking before I get into details - did you read the docs at https://ged4py.readthedocs.io/en/latest/, in particular https://ged4py.readthedocs.io/en/latest/usage.html?

I know docs are probably very terse, if they are not too helpful probably you can tell me how can I improve them?

Cheers,
Andy

**Comment by VK6TGQ** [comment]
Hi Andy,

Thanks – I did look at the documentation at the links you provided.  It looks very comprehensive and well organised.  I am a self-taught Python programmer, and I found it a bit to technical for my level of understanding. 

It would be helpful to me if there were also some short samples of code that implement simple use cases.  For example, code to join a Marriage record with the 2 Individual records and print the values out.

While I was preparing the attached simple example of the problem I was facing, I worked out a way to resolve it.  You will see that in the code I have attached.  However, I suspect that there is a better way to use the functionality available in your module.  For example, maybe the “pointers” and the “model” functionality.  But I can’t work out how to get started with that functionality.  Any guidance on the best way to utilise your module would be gratefully received. 

Thanks so much for making the ged4py module available.  While I am in COVID lockdown I decided to re-write (in python), some gedcom perl scripts I wrote 20 years ago, and never really finished.  The perl scripts produced lists of Births, Deaths, and Marriages; with the details to allow me to request copies of the certificates.

Kind Regards,
Brian

[SampleProgram.txt](https://github.com/andy-z/ged4py/files/5027894/SampleProgram.txt)
[SampleGEDCOM.txt](https://github.com/andy-z/ged4py/files/5027896/SampleGEDCOM.txt)
[SampleOutput.txt](https://github.com/andy-z/ged4py/files/5027897/SampleOutput.txt)

**Comment by andy-z** [comment]
Hi Brian,

sorry for delay, work stuff keeps me busy.

I looked at your script, here are some comments:
- General structure looks OK if you want to iterate over records/sub-records/sub-sub-records and so on. I usually don't do that but nothing prevents you from doing that if you are interest in checking every single record.
- The thing that you do not need to do is to call `read_record()` when you already have a record. `records0()` method already returns you complete Record instance (or its specific subclass) and it calls `read_record()` internally. Same applies to `sub_records` attribute - it has all records in complete form, there is no need to re-read them again. When you do `reader.read_record(record.offset)` it will return you exactly same object as `record`.

I have modified your script slightly to remove all `read_record()` calls and also to get rid of `range(len(...))` which I find more complicated than needs to be. You can just iterate over things, and if you need to know the index then natural Pythonic way for that is to use `enumerate()`. Here is my version of the script:
```
from ged4py import GedcomReader

path = "SampleGEDCOM.ged"

with GedcomReader(path) as reader:

    # Iterate over all Level 0 Records
    #
    for rec0 in reader.records0('FAM'):

        print(" ")
        print(" ")
        print("== Next Level 0 Record ===========================================")

        print("rec0              : ", rec0)
        print("rec0.level        : ", rec0.level)
        print("rec0.xref_id)     : ", rec0.xref_id)
        print("rec0.tag          : ", rec0.tag)
        print("rec0.value        : ", rec0.value)
        print("Sub Record Count  : ", len(rec0.sub_records))

        for i, rec1 in enumerate(rec0.sub_records):

            print(" ")
            print("-- Next Level 1 Record --- ---------------------------------------")

            print("i           : ", i)
            print("rec1.level  : ", rec1.level)
            print("rec1.tag    : ", rec1.tag)
            print("rec1.value  : ", rec1.value)
            print("rec1.offset : ", rec1.offset)

            for j, rec2 in enumerate(rec1.sub_records):

                print(" ")
                print("-- Next Level 2 Record --- ---------------------------------------")

                print("j           : ", j)
                print("rec2.level  : ", rec2.level)
                print("rec2.tag    : ", rec2.tag)
                print("rec2.value  : ", rec2.value)
                print("rec2.offset : ", rec2.offset)

                rec2 = rec1.sub_records[i]

                for k in range(0, len(rec2.sub_records)):

                    print(" ")
                    print("-- Next Level 3 Record --- ---------------------------------------")

                    print("k           : ", k)
                    print("rec3.level  : ", rec3.level)
                    print("rec3.tag    : ", rec3.tag)
                    print("rec3.value  : ", rec3.value)
                    print("rec3.offset : ", rec3.offset)
```

The code that I normally write does not iterate over all sub-records, most frequently I'm interested in specific record tags. To extract records that I need the methods `record.sub_tag_value()` and `sub_tag()` are the most natural way (and sometimes `sub_tags()`). Here is for example a version of the script which iterates over FAM records and extracts MARR/DATE and MARR/PLAC _values_ (as opposed to records themselves) and INDI records that are pointed from FAM record (this is because `sub_tag()` parameter `follow` is True by default, if you set it to False then it will return a [Pointer](https://ged4py.readthedocs.io/en/latest/ged4py.model.html#ged4py.model.Pointer) instance instead of pointed [Individual](https://ged4py.readthedocs.io/en/latest/ged4py.model.html#ged4py.model.Individual). This is all rather trivial:
```
from ged4py import GedcomReader

path = "SampleGEDCOM.ged"

with GedcomReader(path) as reader:

    # Iterate over all Level 0 Records
    #
    for rec0 in reader.records0('FAM'):

        print("")
        print("== Next FAM Record ==")

        # access DATE and PLAC _values_ if they are defined
        marr_date = rec0.sub_tag_value("MARR/DATE")
        marr_plac = rec0.sub_tag_value("MARR/PLAC")
        if marr_date is not None:
            print("Date :", marr_date)
        if marr_date is not None:
            print("Place:", marr_plac)

        # Access INDI _records_ that are referenced from FAM record
        # (follow parameter is True by default)
        print("HUSB :", rec0.sub_tag("HUSB"))
        print("WIFE :", rec0.sub_tag("WIFE"))

        # Can also set follow=False, it will return Pointer record instead
        print("HUSB :", rec0.sub_tag("HUSB", follow=False))
        print("WIFE :", rec0.sub_tag("WIFE", follow=False))
```
The value returned from `record.sub_tag_value(...)` or `record.value` for many record types is a string, but some record types have more complex value types, for example DATE record has a special type [DateValue](https://ged4py.readthedocs.io/en/latest/ged4py.date.html#ged4py.date.DateValue) which is needed to support transformations to different calendars or locales.

I'll expand the documentation with few examples of this kind when I can find time for it.

**Comment by andy-z** [comment]
@VK6TGQ, I have added few examples to the documentation. Also docstrings for few important classes have been extended, I hope documentation is getting better.

Check out the docs: https://ged4py.readthedocs.io/en/latest/index.html
And new examples: https://ged4py.readthedocs.io/en/latest/examples.html
Improved `model` docs: https://ged4py.readthedocs.io/en/latest/ged4py.model.html

**Comment by andy-z** [comment]
Should have mentioned - new release number with all improvements is 0.2.1, though the code did not change compared to 0.2.0, only documentation updates.
